define ocserv::user_config (
  String[1] $username = $name,
  String[1] $mode     = '0600',

  Optional[String[1]] $ipv4_network            = undef,
  Optional[String[1]] $ipv4_netmask            = undef,
  Optional[String[1]] $ipv6_network            = undef,
  Optional[Integer]   $rx_data_per_sec         = undef,
  Optional[Integer]   $tx_data_per_sec         = undef,
  Optional[Boolean]   $expose_iroutes          = undef,
  Optional[Array]     $route                   = undef,
  Optional[String[1]] $no_route                = undef,
  Optional[Integer]   $net_priority            = undef,
  Optional[Boolean]   $deny_roaming            = undef,
  Optional[Boolean]   $no_udp                  = undef,
  Optional[Integer]   $keepalive               = undef,
  Optional[Integer]   $dpd                     = undef,
  Optional[Integer]   $mobile_dpd              = undef,
  Optional[Integer]   $max_same_clients        = undef,
  Optional[Boolean]   $tunnel_all_dns          = undef,
  Optional[Boolean]   $restrict_user_to_routes = undef,
  Optional[String[1]] $restrict_user_to_ports  = undef,
  Optional[String[1]] $cgroup                  = undef,
  Optional[Integer]   $stats_report_time       = undef,
  Optional[Integer]   $mtu                     = undef,
  Optional[Integer]   $idle_timeout            = undef,
  Optional[Integer]   $mobile_idle_timeout     = undef,
  Optional[String[1]] $split_dns               = undef,
  Optional[Integer]   $session_timeout         = undef,
){
  file { "${::ocserv::per_user_conf_dir}/${name}":
    ensure  => file,
    mode    => "${mode}",
    owner   => "${::ocserv::runas_user}",
    group   => "${::ocserv::runas_group}",
    require => File["${::ocserv::per_user_conf_dir}"],
    content => epp("${module_name}/per-user-group-conf.epp", {
      ipv4_network            => $ipv4_network,
      ipv4_netmask            => $ipv4_netmask,
      ipv6_network            => $ipv6_network,
      rx_data_per_sec         => $rx_data_per_sec,
      tx_data_per_sec         => $tx_data_per_sec,
      expose_iroutes          => $expose_iroutes,
      route                   => $route,
      no_route                => $no_route,
      net_priority            => $net_priority,
      deny_roaming            => $deny_roaming,
      no_udp                  => $no_udp,
      keepalive               => $keepalive,
      dpd                     => $dpd,
      mobile_dpd              => $mobile_dpd,
      max_same_clients        => $max_same_clients,
      tunnel_all_dns          => $tunnel_all_dns,
      restrict_user_to_routes => $restrict_user_to_routes,
      cgroup                  => $cgroup,
      stats_report_time       => $stats_report_time,
      mtu                     => $mtu,
      idle_timeout            => $idle_timeout,
      mobile_idle_timeout     => $mobile_idle_timeout,
      restrict_user_to_ports  => $restrict_user_to_ports,
      split_dns               => $split_dns,
      session_timeout         => $session_timeout,
    }),
    notify  => Exec['ocserv-reload'],
  }
}
